/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.macman;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Doctor = new javax.swing.JComboBox<>();
        Patient1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Patient2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Patient3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Patient4 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\JAVA PRO\\IMAGES\\LOGORe.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jLabel2.setText("MAC-Man");

        jButton1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton1.setText("Dash Board");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modify Doctor", " ", " " }));
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });

        Patient1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modify Patient", " " }));
        Patient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Non-Medical Staff Records");

        jLabel4.setText("Doctors Records");

        jLabel5.setText("Patient Records");

        Patient2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modify Staff Personnel" }));
        Patient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Medicine Records");

        Patient3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Medicine", "Expired Medicine", "Stock Availability", " " }));
        Patient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Equipment Records");

        Patient4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Equipment", "Faulty Equipment", "Request Equipment", " " }));
        Patient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Patient3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                        .addComponent(Patient2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Patient4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(Patient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\JAVA PRO\\IMAGES\\SMVD_University_Logo.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, 83, 74));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SMVDU");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 35, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel8.setText("Doctors Registered");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel11.setText("Non-Med Staff");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel12.setText("Medicine Count");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel13.setText("Equipment Count");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel15.setText("Patient Registered");

        jLabel16.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel16.setText("50+");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel17.setText("5000+");

        jLabel18.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel18.setText("1000+");

        jLabel19.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel19.setText("30+");

        jLabel20.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel20.setText("200+");

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(165, 165, 165))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DashBoard db1 = new DashBoard();
            db1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         StartUp su1 = new StartUp();
            su1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        // TODO add your handling code here:
                String selectedItem = Doctor.getSelectedItem().toString();

                if("Modify Doctor".equals(selectedItem)) {
                            DoctorsPage dp = new DoctorsPage();
                            dp.setVisible(true);
                            this.dispose();
                        }
    }//GEN-LAST:event_DoctorActionPerformed

    private void Patient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient1ActionPerformed
        // TODO add your handling code here:
                String selectedItem = Patient1.getSelectedItem().toString();
                 if ("Modify Patient".equals(selectedItem)) {
                            PatientsForm pf = new PatientsForm();
                            pf.setVisible(true);
                            this.dispose();
                        } 

    }//GEN-LAST:event_Patient1ActionPerformed

    private void Patient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient2ActionPerformed
        // TODO add your handling code here:
          String selectedItem = Patient2.getSelectedItem().toString();
        
                 if("Modify Staff Personnel".equals(selectedItem)) {
                            StaffPersonnel sp = new StaffPersonnel();
                            sp.setVisible(true);
                            this.dispose();
                        } 
               
    }//GEN-LAST:event_Patient2ActionPerformed

    private void Patient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient3ActionPerformed
        // TODO add your handling code here:
                String selectedItem = Patient3.getSelectedItem().toString();
        
                if("Add Medicine".equals(selectedItem)) {
                        MedicinePage mp = new MedicinePage();
                        mp.setVisible(true);
                        this.dispose();
                        } 
                else if ("Expired Medicine".equals(selectedItem)) {
                            MedicineExpired me = new MedicineExpired();
                            me.setVisible(true);
                            this.dispose();
                        } 
                else if ("Stock Availability".equals(selectedItem)) {
                            StockAvailMed svm = new StockAvailMed();
                            svm.setVisible(true);
                            this.dispose();
                        } 
        
        
    }//GEN-LAST:event_Patient3ActionPerformed

    private void Patient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient4ActionPerformed
        // TODO add your handling code here:
                String selectedItem = Patient4.getSelectedItem().toString();
        
                if("Add Equipment".equals(selectedItem)) {
                        EquipmentAdd ea = new EquipmentAdd();
                        ea.setVisible(true);
                        this.dispose();
                        } 
                else if ("Faulty Equipment".equals(selectedItem)) {
                            FaultyEquipment fe = new FaultyEquipment();
                            fe.setVisible(true);
                            this.dispose();
                        } 
                else if ("Request Equipment".equals(selectedItem)) {
                            RequestEquipement re = new RequestEquipement();
                            re.setVisible(true);
                            this.dispose();
                        } 
        
    }//GEN-LAST:event_Patient4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Variable to store the count
        int Countpatient = 0;
        int Countdoctor = 0;
        int Countmedicine = 0;
        int Countequipment = 0;
        int Countstaff = 0;
        

        Connection connection = null;
        try {
            // Step 1: Establish connection to the database
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/macmandb", "root", "aditya");
            System.out.println("connected to db");
            
            // Step 2: Execute the PATIENT COUNT query
            String Pquery = "SELECT COUNT(*) AS total_patients FROM Patient;";
            PreparedStatement PpreparedStatement = connection.prepareStatement(Pquery);
            // Step : Retrieve the result set
            ResultSet PresultSet = PpreparedStatement.executeQuery();
            if (PresultSet.next()) {
                Countpatient = PresultSet.getInt("total_patients"); // Retrieve the count value
            }
            // Close resources
            PresultSet.close();
            PpreparedStatement.close();
            
            // Step 3: Execute the DOCTOR COUNT query
            String Dquery = "SELECT COUNT(*) AS total_doctors FROM Doctor;";
            PreparedStatement DpreparedStatement = connection.prepareStatement(Dquery);
            // Step : Retrieve the result set
            ResultSet DresultSet = DpreparedStatement.executeQuery();
            if (DresultSet.next()) {
                Countdoctor = DresultSet.getInt("total_doctors"); // Retrieve the count value
            }
            // Close resources
            DresultSet.close();
            DpreparedStatement.close();
            
            // Step 4: Execute the STAFF COUNT query
            String Squery = "SELECT COUNT(*) AS total_staff FROM Staff;";
            PreparedStatement SpreparedStatement = connection.prepareStatement(Squery);
            // Step : Retrieve the result set
            ResultSet SresultSet = SpreparedStatement.executeQuery();
            if (SresultSet.next()) {
                Countstaff = SresultSet.getInt("total_staff"); // Retrieve the count value
            }
            // Close resources
            SresultSet.close();
            SpreparedStatement.close();
            
             // Step 5: Execute the MEDICINE COUNT query
            String Mquery = "SELECT COUNT(*) AS total_medicine FROM Medicine;";
            PreparedStatement MpreparedStatement = connection.prepareStatement(Mquery);
            // Step : Retrieve the result set
            ResultSet MresultSet = MpreparedStatement.executeQuery();
            if (MresultSet.next()) {
                Countmedicine = MresultSet.getInt("total_medicine"); // Retrieve the count value
            }
            // Close resources
            MresultSet.close();
            MpreparedStatement.close();
            
            ///////////////////////////////////////////////////
            
            // Step 6: Execute the EQUIPMENT COUNT query
            String Equery = "SELECT COUNT(*) AS total_equipment FROM Equipment;";
            PreparedStatement EpreparedStatement = connection.prepareStatement(Equery);
            // Step : Retrieve the result set
            ResultSet EresultSet = EpreparedStatement.executeQuery();
            if (EresultSet.next()) {
                Countequipment = EresultSet.getInt("total_equipment"); // Retrieve the count value
            }
            // Close resources
            EresultSet.close();
            EpreparedStatement.close();

/////////////////////////////////////////////////////////////////////////////////////Another Method         
//            String Equery = "SELECT equipment_id FROM Equipment;";
//            PreparedStatement EpreparedStatement = null;
//            EpreparedStatement = connection.prepareStatement(Equery);
//            ResultSet EresultSet = EpreparedStatement.executeQuery();
//            while(EresultSet.next()){
//                Countequipment=Countequipment+1;
//            }
//            
//            EresultSet.close();
//            EpreparedStatement.close();
////////////////////////////////////////////////////////////////////////////////////// Another Method Ends         
            

            } catch (SQLException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
            }
      
        // Step : Update the JLabel with the Patient count value
        String Pdisplay = String.valueOf(Countpatient);
        jLabel18.setText(Pdisplay);
        
        // Step : Update the JLabel with the Doctor count value
        String Ddisplay = String.valueOf(Countdoctor);
        jLabel16.setText(Ddisplay);
        
        // Step : Update the JLabel with the Non Med Staff count value
        String Sdisplay = String.valueOf(Countstaff);
        jLabel19.setText(Sdisplay);
        
        // Step : Update the JLabel with the Medicine count value
        String Mdisplay = String.valueOf(Countmedicine);
        jLabel17.setText(Mdisplay);
        
        // Step : Update the JLabel with the Patient count value
        String Edisplay = String.valueOf(Countequipment);
        jLabel20.setText(Edisplay);
        
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    static Connection con;
    static java.sql.Statement s;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
        
        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "aditya");
//            System.out.println(con);
//            System.out.println(
//                    "Connection Established successfully");
            s = con.createStatement();
            
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (Exception e) {
            System.out.println("Unkown Exception");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Doctor;
    private javax.swing.JComboBox<String> Patient1;
    private javax.swing.JComboBox<String> Patient2;
    private javax.swing.JComboBox<String> Patient3;
    private javax.swing.JComboBox<String> Patient4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
